name: CICD

on:
  schedule:
    - cron: '*/60 * * * *'

env:
  DOCKER_BUILDKIT: 1 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release-name: ["mainnet", "testnet", "betanet"]
    steps:
      - uses: actions/checkout@v2
      - name: Get Github Tag
        env: 
          RELEASE_NAME: ${{ matrix.release-name }}
        run: |
          regex=""
          if [ "$RELEASE_NAME" == "mainnet" ]; then 
            regex="[0-9]+.[0-9]+.[0-9]+$"
          elif [ "$RELEASE_NAME" == "testnet" ]; then
            regex="[0-9]+.[0-9]+.[0-9]+-rc+"
          elif [ "$RELEASE_NAME" == "betanet" ]; then
            regex="[0-9]+.[0-9]+.[0-9]+-beta+" 
          fi
          echo $(curl -s https://api.github.com/repos/nearprotocol/nearcore/releases | jq -c -r --arg regex "$regex" 'map(select(.tag_name | test($regex)))[0].tag_name') > github-tag.txt

      - name: Get Docker Hub Tags   
        if: ${{ success() }}
        env:
          DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
        run: |
          TOKEN=`curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:$DOCKER_IMAGE_NAME:pull" | jq '.token' | sed 's/"//g'`
          TAGS=`curl -s https://registry.hub.docker.com/v2/$DOCKER_IMAGE_NAME/tags/list -H "Authorization: Bearer $TOKEN" | jq ".tags[]" | sed 's/"//g'`
          github_tag=`cat github-tag.txt`
          for tag in $TAGS;
          do
            # if $github_tag contains in $tag
            if [[ $tag == *"$github_tag"* ]]; then
              echo "Tag:$tag already deployed"
              exit 1
            elif [ -z "$tag" ]; then
              # Create an empty Dockerfile for a Docker image with github tag 
              touch hello && echo "FROM scratch" > Dockerfile
              echo "ADD hello /" >> Dockerfile && echo 'CMD ["/hello"]' >> Dockerfile
            fi
          done
          
          echo ::set-env name=RELEASE_VERSION::$(echo $github_tag)

          # If docker hub is empty
          if [ ${#TAGS[@]} -eq 1 ]; then
              touch hello && echo "FROM scratch" > Dockerfile
              echo "ADD hello /" >> Dockerfile && echo 'CMD ["/hello"]' >> Dockerfile
          fi

      - name: Publish GitHub Tag Image to Registry
        if: ${{ success() }}
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_IMAGE_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ env.RELEASE_VERSION }}

      - name: Install Rust
        if: ${{ success() }}
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly-2020-03-19

      - name: Clone NEARCore
        if: ${{ success() }}
        uses: actions/checkout@v2
        with:
          repository: nearprotocol/nearcore
          ref: ${{ env.RELEASE_VERSION }}

      - name: Cargo Test
        run: cargo test    

      - name: Test Neard
        run: cd neard && cargo test 

      - name: Publish Latest Docker Image to Registry
        if: ${{ success() }}
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_IMAGE_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ matrix.release-name }}
